# Generated by Django 6.1 on 2026-08-10 04:46

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participacoes', '0001_initial'),
        ('projetos', '0002_projeto_segmento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoResposta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('inclui_campos_fixos', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Variavel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('chave', models.CharField(editable=False, max_length=100, unique=True)),
                ('obrigatoria', models.BooleanField(default=False)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variaveis_criadas', to=settings.AUTH_USER_MODEL)),
                ('tipo_resposta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variaveis', to='formularios.tiporesposta')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FormularioVariavel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulario_variaveis', to='formularios.formulario')),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formulario_variaveis', to='formularios.variavel')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='formulario',
            name='variaveis',
            field=models.ManyToManyField(blank=True, related_name='formularios', through='formularios.FormularioVariavel', to='formularios.variavel'),
        ),
        migrations.CreateModel(
            name='VariavelOpcao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=150)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='formularios.variavel')),
            ],
            options={
                'ordering': ['ordem', 'valor'],
            },
        ),
        migrations.CreateModel(
            name='ProjetoFormulario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projeto_formularios', to='formularios.formulario')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projeto_formularios', to='projetos.projeto')),
            ],
            options={
                'ordering': ['ordem'],
                'constraints': [models.UniqueConstraint(fields=('projeto', 'formulario'), name='uniq_projeto_formulario')],
            },
        ),
        migrations.CreateModel(
            name='RespostaFormulario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('respostas_variaveis', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('respondido_em', models.DateTimeField(auto_now=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='formularios.formulario')),
                ('participacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_formularios', to='participacoes.participacao')),
            ],
            options={
                'ordering': ['-respondido_em'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['respostas_variaveis'], name='idx_respostas_variaveis_gin')],
                'constraints': [models.UniqueConstraint(fields=('participacao', 'formulario'), name='uniq_participacao_formulario')],
            },
        ),
        migrations.AddConstraint(
            model_name='formulariovariavel',
            constraint=models.UniqueConstraint(fields=('formulario', 'variavel'), name='uniq_formulario_variavel'),
        ),
    ]
