# Generated by Django 6.1 on 2026-08-10 14:02

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_seed_tipos_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostaformulario',
            name='respostas_variaveis',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
