# Gerado a partir de BP.xlsx (aba "Modelo", colunas Z a CG + CG) — cria os 9
# formulários "Perguntas Básicas de X" com suas variáveis e opções de resposta.
# Dados embutidos aqui (não lidos do .xlsx em tempo de migração) pra a migração
# ser reproduzível em qualquer ambiente, sem depender do arquivo original estar
# presente no deploy.

from django.db import migrations
from django.utils.text import slugify

FORMULARIOS = [   {   'nome': 'Perguntas Básicas de Saúde',
        'perguntas': [   {   'nome': 'Qual é sua principal relação com o tema Saúde?',
                             'tipo': 'select',
                             'opcoes': [   'Trabalho na área',
                                           'Estudo ou pesquiso o tema',
                                           'Tenho experiência pessoal relevante',
                                           'Acompanho bastante o assunto',
                                           'Tenho interesse, mas pouco conhecimento']},
                         {   'nome': 'Sobre quais assuntos de Saúde você tem mais conhecimento?',
                             'tipo': 'multipla_escolha',
                             'opcoes': [   'Saúde física',
                                           'Saúde mental',
                                           'Nutrição',
                                           'Sono e descanso',
                                           'Exercícios e bem-estar',
                                           'Prevenção e qualidade de vida']},
                         {   'nome': 'Com que frequência você acompanha conteúdos sobre Saúde?',
                             'tipo': 'select',
                             'opcoes': [   'Todos os dias',
                                           'Algumas vezes por semana',
                                           'Algumas vezes por mês',
                                           'Raramente',
                                           'Praticamente nunca']},
                         {   'nome': 'De onde vem principalmente seu conhecimento sobre Saúde?',
                             'tipo': 'select',
                             'opcoes': [   'Experiência profissional',
                                           'Formação acadêmica',
                                           'Experiência pessoal',
                                           'Família/amigos',
                                           'Redes sociais e creators',
                                           'Notícias e mídia',
                                           'Livros/artigos/pesquisas']},
                         {   'nome': 'Quais marcas, produtos ou serviços de saúde você utiliza '
                                     'atualmente?',
                             'tipo': 'multipla_escolha',
                             'opcoes': [   'Unimed',
                                           'Amil',
                                           'SulAmérica',
                                           'Bradesco Saúde',
                                           'Hapvida',
                                           'SUS',
                                           'Dasa',
                                           'Fleury',
                                           'Hermes Pardini']},
                         {   'nome': 'Quais tipos de serviços de saúde você utiliza ou já '
                                     'utilizou recentemente?',
                             'tipo': 'multipla_escolha',
                             'opcoes': [   'Plano de saúde',
                                           'Consultas particulares',
                                           'Telemedicina',
                                           'Clínicas populares',
                                           'Laboratórios',
                                           'Farmácias',
                                           'Apps de saúde',
                                           'Academias/serviços de bem-estar']},
                         {   'nome': 'Filhos',
                             'tipo': 'select',
                             'opcoes': ['Não tenho', '1', '2', '3', '4']}]},
    {   'nome': 'Perguntas Básicas de Lifestyle',
        'perguntas': [   {   'nome': 'Qual é sua principal relação com Lifestyle?',
                             'tipo': 'select',
                             'opcoes': [   'Trabalho na área',
                                           'Produzo conteúdo sobre o tema',
                                           'Acompanho bastante',
                                           'Tenho experiência pessoal relevante',
                                           'Estudo o assunto',
                                           'Tenho apenas interesse']},
                         {   'nome': 'Quais temas de Lifestyle você mais domina?',
                             'tipo': 'multipla_escolha',
                             'opcoes': [   'Rotina e hábitos',
                                           'Viagens',
                                           'Moda',
                                           'Casa e decoração',
                                           'Produtividade',
                                           'Bem-estar',
                                           'Vida social e relacionamentos',
                                           'Organização']},
                         {   'nome': 'Com que frequência você acompanha conteúdos sobre '
                                     'Lifestyle?',
                             'tipo': 'select',
                             'opcoes': [   'Todos os dias',
                                           'Algumas vezes por semana',
                                           'Algumas vezes por mês',
                                           'Raramente']},
                         {   'nome': 'Sobre Lifestyle, você teria mais facilidade para:',
                             'tipo': 'select',
                             'opcoes': [   'Dar recomendações',
                                           'Contar experiências',
                                           'Identificar tendências',
                                           'Comparar estilos de vida',
                                           'Compartilhar hábitos e rotina',
                                           'Falar sobre comportamento']},
                         {   'nome': 'Quais marcas de Lifestyle você consome ou acompanha '
                                     'atualmente?',
                             'tipo': 'multipla_escolha',
                             'opcoes': [   'Nike',
                                           'Adidas',
                                           'Puma',
                                           'New Balance',
                                           'Converse',
                                           'Vans',
                                           'Havaianas',
                                           'Melissa',
                                           'Reserva',
                                           'Farm',
                                           'Osklen',
                                           'Schutz',
                                           'Arezzo',
                                           'Renner',
                                           'Zara',
                                           'C&A',
                                           'Riachuelo',
                                           'Uniqlo',
                                           'Levi’s',
                                           'The North Face',
                                           'Natura',
                                           'O Boticário',
                                           'Avon',
                                           'Granado',
                                           'Phebo',
                                           'Quem Disse, Berenice?',
                                           'Sallve',
                                           'Simple Organic',
                                           'La Roche-Posay',
                                           'Neutrogena',
                                           'Sephora',
                                           'MAC',
                                           'Kérastase',
                                           'L’Oréal Paris',
                                           'Dove',
                                           'Vult',
                                           'Melu',
                                           'Tok&Stok',
                                           'Camicado',
                                           'Westwing',
                                           'IKEA',
                                           'Zara Home',
                                           'H&M Home',
                                           'Tramontina',
                                           'Etna',
                                           'Leroy Merlin',
                                           'Casa Riachuelo',
                                           'Starbucks',
                                           'Nespresso',
                                           'Coca-Cola',
                                           'Red Bull',
                                           'Heineken',
                                           'Lindt',
                                           'Nestlé',
                                           'Mãe Terra',
                                           'Nude',
                                           'Bauducco']},
                         {   'nome': 'Em quais categorias você costuma consumir produtos ou '
                                     'serviços de Lifestyle?',
                             'tipo': 'multipla_escolha',
                             'opcoes': [   'Moda',
                                           'Viagens',
                                           'Casa e decoração',
                                           'Fitness',
                                           'Bem-estar',
                                           'Beleza',
                                           'Restaurantes',
                                           'Experiências',
                                           'Outro']}]},
    {   'nome': 'Perguntas Básicas de Banco',
        'perguntas': [   {   'nome': 'Qual é sua principal relação com bancos e serviços '
                                     'financeiros?',
                             'tipo': 'select',
                             'opcoes': [   'Trabalho no setor financeiro/bancário',
                                           'Já trabalhei em banco',
                                           'Tenho conhecimento profissional de finanças',
                                           'Sou um usuário muito interessado no tema',
                                           'Acompanho novidades do setor',
                                           'Tenho apenas experiência como cliente',
                                           'Outro']},
                         {   'nome': 'Quais assuntos relacionados a bancos você conhece melhor?',
                             'tipo': 'multipla_escolha',
                             'opcoes': [   'Contas e cartões',
                                           'Crédito e empréstimos',
                                           'Investimentos',
                                           'Financiamentos',
                                           'Bancos digitais',
                                           'Pix e pagamentos',
                                           'Benefícios e programas de relacionamento',
                                           'Segurança e fraudes',
                                           'Outro']},
                         {   'nome': 'Qual dessas experiências você já teve?',
                             'tipo': 'select',
                             'opcoes': [   'Usei banco digital',
                                           'Troquei de banco',
                                           'Contratei empréstimo/financiamento',
                                           'Investi por meio de banco',
                                           'Tive problemas com banco',
                                           'Comparei diferentes bancos',
                                           'Trabalhei com produtos bancários',
                                           'Nenhuma dessas']},
                         {   'nome': 'Sobre bancos, você se sente mais preparado para:',
                             'tipo': 'select',
                             'opcoes': [   'Explicar como produtos funcionam',
                                           'Comparar bancos e serviços',
                                           'Contar experiências com a instituição',
                                           'Comentar tendências',
                                           'Falar sobre dívidas',
                                           'Analisar novidades do setor',
                                           'Falar sobre diferentes investimentos']},
                         {   'nome': 'Em quais instituições financeiras você possui atualmente '
                                     'uma conta?',
                             'tipo': 'multipla_escolha',
                             'opcoes': [   'Nubank',
                                           'Itaú',
                                           'Bradesco',
                                           'Santander',
                                           'Banco do Brasil',
                                           'Caixa',
                                           'Inter',
                                           'BTG Pactual',
                                           'C6 Bank',
                                           'XP',
                                           'Mercado Pago',
                                           'Outro']},
                         {   'nome': 'Que tipo de conta você possui nessas instituições?',
                             'tipo': 'select',
                             'opcoes': [   'Conta corrente tradicional',
                                           'Conta digital',
                                           'Conta universitária',
                                           'Conta premium/segmento alta renda',
                                           'Conta PJ',
                                           'Conta conjunta',
                                           'Conta de investimentos',
                                           'Outro']}]},
    {   'nome': 'Perguntas Básicas de Beleza',
        'perguntas': [   {   'nome': 'Qual é sua principal relação com Beleza?',
                             'tipo': 'select',
                             'opcoes': [   'Trabalho na área',
                                           'Produzo conteúdo',
                                           'Tenho formação na área',
                                           'Sou muito interessado(a)',
                                           'Acompanho tendências',
                                           'Tenho experiência pessoal relevante',
                                           'Outro']},
                         {   'nome': 'Quais temas de Beleza você conhece melhor?',
                             'tipo': 'multipla_escolha',
                             'opcoes': [   'Skincare',
                                           'Maquiagem',
                                           'Cabelo',
                                           'Perfumes',
                                           'Estética',
                                           'Procedimentos',
                                           'Produtos de beleza',
                                           'Tendências']},
                         {   'nome': 'Com que frequência você acompanha novidades de Beleza?',
                             'tipo': 'select',
                             'opcoes': [   'Todos os dias',
                                           'Algumas vezes por semana',
                                           'Algumas vezes por mês',
                                           'Raramente']},
                         {   'nome': 'O que mais influencia suas escolhas de produtos de Beleza?',
                             'tipo': 'select',
                             'opcoes': [   'Recomendações de especialistas',
                                           'Influenciadores',
                                           'Amigos/família',
                                           'Avaliações na internet',
                                           'Marca',
                                           'Preço',
                                           'Ingredientes/composição',
                                           'Tendências']},
                         {   'nome': 'Quais marcas de beleza você utiliza atualmente?',
                             'tipo': 'multipla_escolha',
                             'opcoes': [   'Natura',
                                           'O Boticário',
                                           'Avon',
                                           'Eudora',
                                           'Quem Disse, Berenice?',
                                           'Vult',
                                           'Ruby Rose',
                                           'Dailus',
                                           'Boca Rosa',
                                           'Niina Secrets',
                                           'Bruna Tavares',
                                           'Fran by Franciny Ehlke',
                                           'Mari Maria',
                                           'Max Love',
                                           'Melu',
                                           'Luisance',
                                           'Jasmyne',
                                           'Ruby Kisses',
                                           'Catharine Hill',
                                           'Océane',
                                           'Pink 21',
                                           'Sallve',
                                           'Principia',
                                           'Needs',
                                           'Simple Organic',
                                           'Creamy',
                                           'Beyoung',
                                           'Tracta',
                                           'Nivea',
                                           'Neutrogena',
                                           'Garnier',
                                           "L'Oréal Paris",
                                           'Dove',
                                           'CeraVe',
                                           'La Roche-Posay',
                                           'Vichy',
                                           'Bioderma',
                                           'Lola Cosmetics',
                                           'Salon Line',
                                           'Seda',
                                           'Skala',
                                           'Novex',
                                           'Haskell',
                                           'Bio Extratus',
                                           'Elseve',
                                           'Pantene',
                                           'Tresemmé',
                                           'Wella',
                                           'Kérastase',
                                           'Truss',
                                           'Phebo',
                                           'Granado',
                                           'Giovanna Baby',
                                           'Monange',
                                           'Paixão',
                                           'MAC',
                                           'Sephora',
                                           'Estée Lauder',
                                           'Clinique',
                                           'Lancôme',
                                           'Dior',
                                           'Chanel',
                                           'Rare Beauty',
                                           'Fenty Beauty',
                                           'Charlotte Tilbury',
                                           'Benefit',
                                           'NARS',
                                           'Maybelline',
                                           'NYX',
                                           'Kiko Milano',
                                           'The Ordinary',
                                           'Glossier',
                                           'Sol de Janeiro',
                                           'Aesop']},
                         {   'nome': 'Em quais categorias de produtos de beleza você costuma '
                                     'comprar?',
                             'tipo': 'multipla_escolha',
                             'opcoes': [   'Skincare',
                                           'Maquiagem',
                                           'Cabelo',
                                           'Perfume',
                                           'Protetor solar',
                                           'Higiene pessoal',
                                           'Produtos para barba',
                                           'Procedimentos/estética',
                                           'Outro']}]},
    {   'nome': 'Perguntas Básicas de Esporte',
        'perguntas': [   {   'nome': 'Qual é sua principal relação com Esporte?',
                             'tipo': 'select',
                             'opcoes': [   'Sou atleta',
                                           'Pratico regularmente',
                                           'Trabalho no setor',
                                           'Estudo o tema',
                                           'Sou torcedor/fã',
                                           'Acompanho notícias e competições',
                                           'Tenho interesse casual']},
                         {   'nome': 'Quais esportes você acompanha ou pratica?',
                             'tipo': 'multipla_escolha',
                             'opcoes': [   'Futebol',
                                           'Corrida',
                                           'Academia/musculação',
                                           'Ciclismo',
                                           'Tênis',
                                           'Lutas',
                                           'Esportes olímpicos',
                                           'Esportes radicais',
                                           'Outro']},
                         {   'nome': 'Com que frequência você acompanha Esporte?',
                             'tipo': 'select',
                             'opcoes': [   'Todos os dias',
                                           'Algumas vezes por semana',
                                           'Algumas vezes por mês',
                                           'Apenas em grandes eventos',
                                           'Raramente']},
                         {   'nome': 'De onde vem seu conhecimento sobre Esporte?',
                             'tipo': 'select',
                             'opcoes': [   'Prática pessoal',
                                           'Experiência profissional',
                                           'Formação',
                                           'Competições',
                                           'Notícias',
                                           'Redes sociais',
                                           'Comunidade/grupo esportivo',
                                           'Outro']},
                         {   'nome': 'Sobre Esporte, você teria mais facilidade para:',
                             'tipo': 'select',
                             'opcoes': [   'Analisar competições',
                                           'Falar sobre atletas',
                                           'Compartilhar experiências',
                                           'Explicar técnicas',
                                           'Comentar tendências',
                                           'Falar sobre treinamento e rotina',
                                           'Outro']},
                         {   'nome': 'Quais marcas esportivas você utiliza ou acompanha '
                                     'atualmente?',
                             'tipo': 'multipla_escolha',
                             'opcoes': [   'Nike',
                                           'Adidas',
                                           'Puma',
                                           'Asics',
                                           'New Balance',
                                           'Olympikus',
                                           'Under Armour',
                                           'Mizuno',
                                           'Centauro',
                                           'Decathlon',
                                           'Outro']},
                         {   'nome': 'Quais produtos ou serviços esportivos você utiliza '
                                     'atualmente?',
                             'tipo': 'multipla_escolha',
                             'opcoes': [   'Academia',
                                           'Corrida',
                                           'Aplicativos de treino',
                                           'Relógios/smartwatches',
                                           'Tênis esportivos',
                                           'Roupas esportivas',
                                           'Suplementos',
                                           'Clubes/associações esportivas',
                                           'Outro']}]},
    {   'nome': 'Perguntas Básicas de Entretenimento',
        'perguntas': [   {   'nome': 'Quais áreas de Entretenimento você mais acompanha?',
                             'tipo': 'multipla_escolha',
                             'opcoes': [   'Filmes',
                                           'Séries',
                                           'Música',
                                           'TV',
                                           'Streaming',
                                           'Games',
                                           'Cultura pop',
                                           'Celebridades',
                                           'Eventos',
                                           'Outro']},
                         {   'nome': 'Com que frequência você consome conteúdos de '
                                     'Entretenimento?',
                             'tipo': 'select',
                             'opcoes': [   'Todos os dias',
                                           'Algumas vezes por semana',
                                           'Algumas vezes por mês',
                                           'Raramente']},
                         {   'nome': 'Onde você mais acompanha novidades?',
                             'tipo': 'select',
                             'opcoes': [   'Instagram',
                                           'TikTok',
                                           'YouTube',
                                           'X/Twitter',
                                           'Sites e portais',
                                           'Streaming',
                                           'Podcasts',
                                           'Amigos/comunidades',
                                           'Outro']},
                         {   'nome': 'Que tipo de conteúdo de Entretenimento você mais gosta de '
                                     'discutir?',
                             'tipo': 'select',
                             'opcoes': [   'Lançamentos',
                                           'Críticas e opiniões',
                                           'Bastidores',
                                           'Celebridades',
                                           'Tendências',
                                           'Cultura pop',
                                           'Música',
                                           'Filmes e séries',
                                           'Games',
                                           'Outro']},
                         {   'nome': 'Sobre Entretenimento, você se considera:',
                             'tipo': 'select',
                             'opcoes': [   'Muito bem informado(a)',
                                           'Bem informado(a)',
                                           'Interessado(a) e atualizado(a)',
                                           'Interessado(a), mas pouco atualizado(a)',
                                           'Consumidor(a) casual']},
                         {   'nome': 'Quais plataformas de entretenimento você assina ou utiliza '
                                     'atualmente?',
                             'tipo': 'multipla_escolha',
                             'opcoes': [   'Netflix',
                                           'Disney+',
                                           'Prime Video',
                                           'Max',
                                           'Globoplay',
                                           'Apple TV+',
                                           'Spotify',
                                           'YouTube Premium',
                                           'Crunchyroll',
                                           'Outro']},
                         {   'nome': 'Quais tipos de conteúdo você mais consome nessas '
                                     'plataformas?',
                             'tipo': 'multipla_escolha',
                             'opcoes': [   'Filmes',
                                           'Séries',
                                           'Documentários',
                                           'Esportes',
                                           'Música',
                                           'Podcasts',
                                           'Reality shows',
                                           'Animes',
                                           'Games',
                                           'Outro']}]},
    {   'nome': 'Perguntas Básicas de Tecnologia',
        'perguntas': [   {   'nome': 'Qual é sua principal relação com Tecnologia?',
                             'tipo': 'select',
                             'opcoes': [   'Trabalho na área',
                                           'Estudo tecnologia',
                                           'Desenvolvo produtos/soluções',
                                           'Uso tecnologia intensivamente no trabalho',
                                           'Sou entusiasta',
                                           'Acompanho novidades',
                                           'Tenho interesse geral']},
                         {   'nome': 'Quais temas de Tecnologia você conhece melhor?',
                             'tipo': 'multipla_escolha',
                             'opcoes': [   'Inteligência artificial',
                                           'Celulares e computadores',
                                           'Apps e plataformas',
                                           'Games',
                                           'Redes sociais',
                                           'Segurança digital',
                                           'Startups',
                                           'Gadgets',
                                           'Tecnologia para trabalho',
                                           'Outro']},
                         {   'nome': 'Com que frequência você acompanha novidades de Tecnologia?',
                             'tipo': 'select',
                             'opcoes': [   'Todos os dias',
                                           'Algumas vezes por semana',
                                           'Algumas vezes por mês',
                                           'Raramente']},
                         {   'nome': 'Como você costuma descobrir novas tecnologias?',
                             'tipo': 'select',
                             'opcoes': [   'Redes sociais',
                                           'YouTube',
                                           'Sites especializados',
                                           'Trabalho',
                                           'Amigos/comunidades',
                                           'Eventos',
                                           'Testando produtos',
                                           'Outro']},
                         {   'nome': 'Sobre Tecnologia, você teria mais facilidade para:',
                             'tipo': 'select',
                             'opcoes': [   'Explicar novidades',
                                           'Avaliar produtos',
                                           'Testar ferramentas',
                                           'Identificar tendências',
                                           'Falar sobre impactos da tecnologia',
                                           'Compartilhar experiências de uso',
                                           'Outro']},
                         {   'nome': 'Quais marcas de tecnologia você utiliza atualmente?',
                             'tipo': 'multipla_escolha',
                             'opcoes': [   'Apple',
                                           'Samsung',
                                           'Google',
                                           'Xiaomi',
                                           'Motorola',
                                           'Lenovo',
                                           'Dell',
                                           'Microsoft',
                                           'Sony',
                                           'Outro']},
                         {   'nome': 'Quais dispositivos ou serviços de tecnologia você utiliza '
                                     'atualmente?',
                             'tipo': 'multipla_escolha',
                             'opcoes': [   'iPhone/smartphone',
                                           'Notebook/computador',
                                           'Tablet',
                                           'Smartwatch',
                                           'Console de videogame',
                                           'Smart TV',
                                           'Serviços de armazenamento em nuvem',
                                           'Ferramentas de IA',
                                           'Outro']}]},
    {   'nome': 'Perguntas Básicas de Bebidas',
        'perguntas': [   {   'nome': 'Qual é sua principal relação com Bebidas?',
                             'tipo': 'select',
                             'opcoes': [   'Trabalho no setor',
                                           'Tenho conhecimento profissional',
                                           'Sou consumidor(a) e entusiasta',
                                           'Produzo conteúdo',
                                           'Estudo o tema',
                                           'Acompanho tendências',
                                           'Tenho interesse geral']},
                         {   'nome': 'Quais tipos de bebidas você conhece melhor?',
                             'tipo': 'multipla_escolha',
                             'opcoes': [   'Café',
                                           'Cerveja',
                                           'Vinhos',
                                           'Destilados e coquetéis',
                                           'Bebidas não alcoólicas',
                                           'Energéticos',
                                           'Chás',
                                           'Bebidas funcionais',
                                           'Outro']},
                         {   'nome': 'Como você costuma descobrir novas bebidas ou marcas?',
                             'tipo': 'select',
                             'opcoes': [   'Amigos',
                                           'Restaurantes e bares',
                                           'Redes sociais',
                                           'Eventos',
                                           'Viagens',
                                           'Lojas',
                                           'Trabalho',
                                           'Outro']},
                         {   'nome': 'O que mais influencia sua escolha de uma bebida?',
                             'tipo': 'select',
                             'opcoes': [   'Sabor',
                                           'Preço',
                                           'Marca',
                                           'Qualidade',
                                           'Ingredientes',
                                           'Recomendação',
                                           'Tendências',
                                           'Experiência/ocasião']},
                         {   'nome': 'Sobre Bebidas, você teria mais facilidade para:',
                             'tipo': 'select',
                             'opcoes': [   'Recomendar produtos',
                                           'Avaliar sabores',
                                           'Falar sobre tendências',
                                           'Comparar marcas',
                                           'Compartilhar experiências',
                                           'Explicar processos de produção',
                                           'Outro']},
                         {   'nome': 'Quais marcas de bebidas você costuma consumir atualmente?',
                             'tipo': 'multipla_escolha',
                             'opcoes': [   'Coca-Cola',
                                           'Pepsi',
                                           'Red Bull',
                                           'Heineken',
                                           'Ambev',
                                           'Stella Artois',
                                           'Corona',
                                           'Nespresso',
                                           '3 Corações',
                                           'Outro']},
                         {   'nome': 'Quais categorias de bebidas você costuma consumir?',
                             'tipo': 'multipla_escolha',
                             'opcoes': [   'Café',
                                           'Refrigerante',
                                           'Cerveja',
                                           'Vinho',
                                           'Destilados/coquetéis',
                                           'Energéticos',
                                           'Água',
                                           'Chá',
                                           'Bebidas funcionais',
                                           'Outro']}]},
    {   'nome': 'Perguntas Básicas de Alimentação',
        'perguntas': [   {   'nome': 'Qual é sua principal relação com Alimentação?',
                             'tipo': 'select',
                             'opcoes': [   'Trabalho na área',
                                           'Estudo o tema',
                                           'Produzo conteúdo',
                                           'Sou apaixonado(a) por gastronomia',
                                           'Tenho conhecimentos adquiridos por experiência',
                                           'Acompanho tendências',
                                           'Tenho interesse geral']},
                         {   'nome': 'Quais temas de Alimentação você conhece melhor?',
                             'tipo': 'multipla_escolha',
                             'opcoes': [   'Gastronomia',
                                           'Culinária',
                                           'Nutrição',
                                           'Restaurantes',
                                           'Receitas',
                                           'Produtos e ingredientes',
                                           'Alimentação saudável',
                                           'Tendências gastronômicas',
                                           'Outro']},
                         {   'nome': 'Com que frequência você acompanha conteúdos sobre '
                                     'Alimentação?',
                             'tipo': 'select',
                             'opcoes': [   'Todos os dias',
                                           'Algumas vezes por semana',
                                           'Algumas vezes por mês',
                                           'Raramente']},
                         {   'nome': 'O que mais influencia suas escolhas alimentares?',
                             'tipo': 'select',
                             'opcoes': [   'Sabor',
                                           'Saúde',
                                           'Preço',
                                           'Praticidade',
                                           'Qualidade dos ingredientes',
                                           'Recomendações',
                                           'Cultura/tradição',
                                           'Novidades e tendências']},
                         {   'nome': 'Sobre Alimentação, você teria mais facilidade para:',
                             'tipo': 'select',
                             'opcoes': [   'Recomendar restaurantes',
                                           'Compartilhar receitas',
                                           'Falar sobre ingredientes',
                                           'Avaliar tendências',
                                           'Contar experiências gastronômicas',
                                           'Explicar hábitos alimentares',
                                           'Outro']},
                         {   'nome': 'Quais marcas ou redes de alimentação você costuma consumir '
                                     'atualmente?',
                             'tipo': 'multipla_escolha',
                             'opcoes': [   '1900 Pizzeria',
                                           '99Food',
                                           'Abbraccio',
                                           'Aoyama',
                                           'Assaí',
                                           'Atacadão',
                                           'Bacio di Latte',
                                           "Bob's",
                                           'Bobs Sorvetes',
                                           'Brasil Cacau',
                                           'Bullguer',
                                           'Burger King',
                                           'Cabana Burger',
                                           'Cacau Show',
                                           'Carrefour',
                                           'Casa Bauducco',
                                           'Casa do Pão de Queijo',
                                           'China in Box',
                                           'China in Box',
                                           'Chiquinho Sorvetes',
                                           'Coco Bambu',
                                           'Divino Fogão',
                                           "Domino's",
                                           "Dunkin'",
                                           'Flying Sushi',
                                           'Gendai',
                                           'Giraffas',
                                           'Griletto',
                                           'Gurume',
                                           "Habib's",
                                           'Havanna',
                                           'Hortifruti',
                                           'iFood',
                                           'Jeronimo',
                                           'Jin Jin',
                                           'Johnny Rockets',
                                           'KFC',
                                           'Koni',
                                           'Kopenhagen',
                                           'Madero',
                                           'Makis Place',
                                           "McDonald's",
                                           'Oakberry',
                                           'Ofner',
                                           'Outback',
                                           'Pão de Açúcar',
                                           'Parmê',
                                           'Patroni',
                                           'Patties',
                                           'Pecorino',
                                           'Pizza Hut',
                                           'Pizzaria Veridiana',
                                           'Popeyes',
                                           'Ragazzo',
                                           'Rappi',
                                           'Rei do Mate',
                                           'Sodiê Doces',
                                           'Spoleto',
                                           'Starbucks',
                                           'Subway',
                                           'Sushiloko',
                                           'Taco Bell',
                                           'The Coffee',
                                           'The Fifties',
                                           "Wendy's",
                                           'Yoi!',
                                           'Zé Delivery']},
                         {   'nome': 'Quais tipos de produtos ou serviços de alimentação você '
                                     'costuma consumir?',
                             'tipo': 'multipla_escolha',
                             'opcoes': [   'Restaurantes',
                                           'Fast food',
                                           'Delivery',
                                           'Supermercados',
                                           'Produtos congelados',
                                           'Produtos naturais/orgânicos',
                                           'Alimentos premium',
                                           'Kits/refeições prontas',
                                           'Produtos de culinária',
                                           'Outro']}]}]


def criar_formularios_e_variaveis(apps, schema_editor):
    Formulario = apps.get_model("formularios", "Formulario")
    Variavel = apps.get_model("formularios", "Variavel")
    VariavelOpcao = apps.get_model("formularios", "VariavelOpcao")
    TipoResposta = apps.get_model("formularios", "TipoResposta")
    FormularioVariavel = apps.get_model("formularios", "FormularioVariavel")

    tipos = {t.codigo: t for t in TipoResposta.objects.all()}
    chaves_usadas = set(Variavel.objects.values_list("chave", flat=True))

    def gerar_chave(nome):
        # Mesma lógica de Variavel._gerar_chave() — reescrita aqui porque o
        # model histórico do apps.get_model() não carrega métodos customizados.
        base = slugify(nome, allow_unicode=False).replace("-", "_") or "variavel"
        candidata = base
        sufixo = 2
        while candidata in chaves_usadas:
            candidata = f"{base}_{sufixo}"
            sufixo += 1
        chaves_usadas.add(candidata)
        return candidata

    for bloco in FORMULARIOS:
        formulario = Formulario.objects.create(
            nome=bloco["nome"],
            descricao="Perguntas de perfilamento geradas a partir do BP.xlsx.",
            inclui_campos_fixos=False,
            ativo=True,
        )
        for ordem, pergunta in enumerate(bloco["perguntas"]):
            variavel = Variavel.objects.create(
                nome=pergunta["nome"],
                chave=gerar_chave(pergunta["nome"]),
                tipo_resposta=tipos[pergunta["tipo"]],
                obrigatoria=False,
                ativa=True,
            )
            for indice, valor in enumerate(pergunta["opcoes"]):
                VariavelOpcao.objects.create(variavel=variavel, valor=valor, ordem=indice)
            FormularioVariavel.objects.create(formulario=formulario, variavel=variavel, ordem=ordem)


def remover_formularios_e_variaveis(apps, schema_editor):
    Formulario = apps.get_model("formularios", "Formulario")
    Variavel = apps.get_model("formularios", "Variavel")

    nomes_formularios = [bloco["nome"] for bloco in FORMULARIOS]
    nomes_perguntas = [p["nome"] for bloco in FORMULARIOS for p in bloco["perguntas"]]
    # Formulario primeiro (cascade derruba FormularioVariavel, que é o que
    # protegia a Variavel de ser apagada); só depois a Variavel (cascade
    # derruba VariavelOpcao).
    Formulario.objects.filter(nome__in=nomes_formularios).delete()
    Variavel.objects.filter(nome__in=nomes_perguntas).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0005_remove_projetoformulario'),
    ]

    operations = [
        migrations.RunPython(criar_formularios_e_variaveis, remover_formularios_e_variaveis),
    ]
