# Generated by Django 6.1 on 2026-08-09 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quando', models.DateTimeField(auto_now_add=True)),
                ('titular', models.CharField(help_text='Código do participante (titular dos dados)', max_length=20)),
                ('acao', models.CharField(choices=[('VISUALIZACAO', 'Visualização'), ('PAGAMENTO', 'Pagamento'), ('ALTERACAO', 'Alteração')], max_length=20)),
                ('detalhe', models.CharField(blank=True, max_length=255)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-quando'],
            },
        ),
    ]
