# Generated by Django 6.1 on 2026-08-13 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text="Ex.: 'pessoas', 'participacoes'", max_length=30)),
                ('quando', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads_em_massa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-quando'],
            },
        ),
    ]
