# Generated by Django 6.1 on 2026-08-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_downloadregistro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroacesso',
            name='acao',
            field=models.CharField(choices=[('VISUALIZACAO', 'Visualização'), ('PAGAMENTO', 'Pagamento'), ('ALTERACAO', 'Alteração')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='registroacesso',
            name='quando',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='registroacesso',
            name='titular',
            field=models.CharField(db_index=True, help_text='Código do participante (titular dos dados)', max_length=20),
        ),
    ]
