# Generated by Django 6.1 on 2026-08-09 06:32

import django.core.validators
import django.db.models.deletion
import pessoas.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[pessoas.validators.validar_cpf])),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(blank=True, choices=[('FEMININO', 'Feminino'), ('MASCULINO', 'Masculino'), ('OUTRO', 'Outro'), ('NAO_INFORMA', 'Prefere não informar')], max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[A-Za-z]{2}$', 'Use a sigla do estado (2 letras).')])),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('escolaridade', models.CharField(blank=True, choices=[('FUNDAMENTAL', 'Fundamental'), ('MEDIO', 'Médio'), ('SUPERIOR', 'Superior'), ('POS', 'Pós-graduação')], max_length=20)),
                ('profissao', models.CharField(blank=True, max_length=100)),
                ('faixa_renda', models.CharField(blank=True, choices=[('A_B', 'Classes A/B'), ('C', 'Classe C'), ('D_E', 'Classes D/E')], max_length=10)),
                ('situacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('DESCARTADO', 'Descartado')], default='PENDENTE', max_length=20)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('PIX', 'PIX'), ('TRANSFERENCIA', 'Transferência')], max_length=20)),
                ('chave_pix', models.CharField(blank=True, max_length=140)),
                ('consentimento_lgpd', models.BooleanField(default=False)),
                ('consentimento_versao', models.CharField(blank=True, max_length=20)),
                ('data_ultima_participacao', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participantes_criados', to=settings.AUTH_USER_MODEL)),
                ('origem_recrutador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participantes_indicados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
