# Generated by Django 6.1 on 2026-08-09 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('termos', '0001_initial'),
    ]

    operations = [
        # O campo era um CharField (texto livre) na Fase 1; ninguém ainda dependia dele para
        # apontar uma versão real. Zeramos os valores existentes antes de trocar o tipo da
        # coluna para FK, porque um texto em branco ('') não converte para bigint.
        migrations.RunSQL(
            sql=(
                "ALTER TABLE pessoas_participante ALTER COLUMN consentimento_versao DROP NOT NULL;"
                "UPDATE pessoas_participante SET consentimento_versao = NULL;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='participante',
            name='consentimento_versao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participantes_aceitantes', to='termos.versaotermo'),
        ),
    ]
