# Generated by Django 6.1 on 2026-08-13 04:45

from django.db import migrations, models

# Só cria a tabela Profissao e o campo `especialidade` aqui. A troca do
# campo `profissao` de texto livre pra FK fica em migrações separadas
# (0005 semeia a lista, 0006 migra os dados e só então troca o tipo do
# campo) — trocar CharField por ForeignKey direto numa `AlterField` faria o
# Postgres tentar converter o texto existente ("Programador" etc.) pra
# bigint e quebrar a migração.


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_participante_bairro_alter_participante_uf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tem_especialidade', models.BooleanField(default=False, help_text='Ex.: Médico, Professor, Analista de TI — abre campo de especialidade.')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='participante',
            name='especialidade',
            field=models.CharField(blank=True, help_text='Só preenchido quando a profissão tem especialidade.', max_length=150),
        ),
    ]
