# Generated by Django 6.1 on 2026-08-13 18:45

import pessoas.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0006_participante_profissao_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='cadastro_incompleto',
            field=models.BooleanField(default=False, help_text='Marcado automaticamente quando o cadastro veio de um lote legado sem telefone, data de nascimento, UF, cidade ou CPF — algum desses campos ficou com um valor de preenchimento ("Não informado"/data placeholder) em vez do dado real. Sinaliza quem precisa ser procurado pra completar o cadastro depois.'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='cpf',
            field=models.CharField(max_length=14, null=True, unique=True, validators=[pessoas.validators.validar_cpf]),
        ),
    ]
