# Generated by Django 6.1 on 2026-08-14 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0007_lote_legado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='faixa_renda',
        ),
        migrations.AddField(
            model_name='participante',
            name='estado_civil',
            field=models.CharField(choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('UNIAO_ESTAVEL', 'União estável'), ('SEPARADO', 'Separado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='ocupacao',
            field=models.CharField(choices=[('OCUPACAO_REMUNERADA', 'Ocupação remunerada'), ('ESTUDANTE_E_OCUPACAO', 'Estudante e ocupação remunerada'), ('ESTUDANTE', 'Estudante'), ('DESEMPREGADO', 'Desempregado(a)'), ('APOSENTADO', 'Aposentado(a)'), ('ATIVIDADES_DO_LAR', 'Atividades do lar')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='raca',
            field=models.CharField(choices=[('BRANCA', 'Branca'), ('PRETA', 'Preta'), ('PARDA', 'Parda'), ('AMARELA', 'Amarela'), ('INDIGENA', 'Indígena')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='regiao',
            field=models.CharField(choices=[('NORTE', 'Norte'), ('NORDESTE', 'Nordeste'), ('CENTRO_OESTE', 'Centro-Oeste'), ('SUDESTE', 'Sudeste'), ('SUL', 'Sul')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='renda_familiar',
            field=models.CharField(choices=[('A', 'A — 20 salários mínimos'), ('B', 'B — 10 a 20 salários mínimos'), ('C', 'C — 4 a 10 salários mínimos'), ('D', 'D — 2 a 4 salários mínimos'), ('E', 'E — até 2 salários mínimos')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='renda_individual',
            field=models.CharField(choices=[('A', 'A — a partir de R$ 9.738'), ('B', 'B — R$ 4.869 a R$ 9.737'), ('C', 'C — R$ 1.883 a R$ 4.868'), ('D', 'D — R$ 974 a R$ 1.882'), ('E', 'E — até R$ 973')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='bairro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='participante',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='participante',
            name='escolaridade',
            field=models.CharField(choices=[('MEDIO_INCOMPLETO', 'Ensino Médio Incompleto'), ('MEDIO_COMPLETO', 'Ensino Médio Completo'), ('SUPERIOR_INCOMPLETO', 'Ensino Superior Incompleto'), ('SUPERIOR_COMPLETO', 'Ensino Superior Completo'), ('POS_GRADUACAO', 'Pós Graduação'), ('MESTRADO', 'Mestrado'), ('DOUTORADO', 'Doutorado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='participante',
            name='genero',
            field=models.CharField(choices=[('MULHER_CIS', 'Mulher cisgênero'), ('HOMEM_CIS', 'Homem cisgênero'), ('MULHER_TRANS', 'Mulher transgênero'), ('HOMEM_TRANS', 'Homem transgênero'), ('NAO_BINARIA', 'Pessoa não binária'), ('OUTRA', 'Outra identidade de gênero'), ('NAO_RESPONDE', 'Prefiro não responder')], max_length=20),
        ),
        migrations.AlterField(
            model_name='participante',
            name='profissao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participantes', to='pessoas.profissao'),
        ),
    ]
