# Generated by Django 6.1 on 2026-08-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0008_campos_perfilamento_bp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='cep',
            field=models.CharField(max_length=9),
        ),
    ]
