# Generated by Django 6.1 on 2026-08-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0010_corrige_genero_legado'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='origem_cadastro',
            field=models.CharField(blank=True, choices=[('PUBLICO', 'Cadastro público'), ('IMPORTACAO_LEGADO', 'Participante legado — importação'), ('IMPORTACAO', 'Importação em lote'), ('MANUAL_EQUIPE', 'Cadastro manual (equipe)')], max_length=20, null=True),
        ),
    ]
