# Generated by Django 6.1 on 2026-08-21 02:29

import re

from django.db import migrations, models


def normalizar_telefones_existentes(apps, schema_editor):
    # Telefone passou a ser sempre gravado só com dígitos (`ParticipanteForm.
    # clean_telefone`/`wizard_csv.py`) — sem isso, a busca por telefone
    # (`icontains` contra um texto só de números) não achava quem já estava
    # cadastrado com "(11) 99999-8888" em vez de "11999998888". Normaliza o
    # que já existe pra ficar consistente com o que passa a ser gravado
    # daqui pra frente.
    Participante = apps.get_model("pessoas", "Participante")
    for participante in Participante.objects.exclude(telefone=""):
        limpo = re.sub(r"\D", "", participante.telefone)
        if limpo != participante.telefone:
            participante.telefone = limpo
            participante.save(update_fields=["telefone"])


def reverter_normalizacao(apps, schema_editor):
    # Não dá pra recuperar a pontuação original (nunca foi guardada em
    # nenhum outro lugar) — reversão não desfaz o formato, só existe pra a
    # migração ser reversível estruturalmente.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0011_participante_origem_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='cadastro_incompleto',
            field=models.BooleanField(db_index=True, default=False, help_text='Marcado automaticamente quando o cadastro veio de um lote legado sem telefone, data de nascimento, UF, cidade ou CPF — algum desses campos ficou com um valor de preenchimento ("Não informado"/data placeholder) em vez do dado real. Sinaliza quem precisa ser procurado pra completar o cadastro depois.'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='participante',
            name='nome',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='participante',
            name='renda_individual',
            field=models.CharField(choices=[('A', 'A — a partir de R$ 9.738'), ('B', 'B — R$ 4.869 a R$ 9.737'), ('C', 'C — R$ 1.883 a R$ 4.868'), ('D', 'D — R$ 974 a R$ 1.882'), ('E', 'E — até R$ 973')], db_index=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='situacao',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('DESCARTADO', 'Descartado')], db_index=True, default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='participante',
            name='telefone',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='participante',
            name='uf',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], db_index=True, max_length=2),
        ),
        migrations.RunPython(normalizar_telefones_existentes, reverter_normalizacao),
    ]
