# Generated by Django 6.1 on 2026-08-09 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cliente', models.CharField(max_length=150)),
                ('metodologia', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('RECRUTANDO', 'Recrutando'), ('EM_CAMPO', 'Em campo'), ('CONCLUIDO', 'Concluído')], default='RECRUTANDO', max_length=20)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('incentivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_perfil', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vagas', models.PositiveIntegerField(default=0)),
                ('descricao', models.TextField(blank=True)),
                ('perfil_idade_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('perfil_idade_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('perfil_genero', models.CharField(blank=True, max_length=20)),
                ('perfil_regiao', models.CharField(blank=True, max_length=100)),
                ('perfil_renda', models.CharField(blank=True, max_length=10)),
                ('perfil_criterios_livres', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
