# Generated by Django 6.1 on 2026-08-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='segmento',
            field=models.CharField(blank=True, choices=[('SAUDE', 'Saúde'), ('COSMETICOS', 'Cosméticos'), ('ALIMENTACAO', 'Alimentação'), ('BANCO', 'Banco'), ('TECNOLOGIA', 'Tecnologia'), ('OUTRO', 'Outro')], max_length=20),
        ),
    ]
