# Generated by Django 6.1 on 2026-08-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_projeto_segmento'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='marca',
            field=models.CharField(blank=True, help_text='Ex.: Adidas.', max_length=150),
        ),
    ]
