# Generated by Django 6.1 on 2026-08-14 02:32
# Dividida manualmente a partir da migração combinada que o Django propôs —
# aqui só cria a estrutura nova (mantendo Perfil.formulario intocado, ainda
# não removido) pra dar espaço pra migração seguinte copiar o dado antes que
# ele suma. Ver 0007 (backfill) e 0008 (remove o campo antigo).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0005_remove_projetoformulario'),
        ('projetos', '0005_seed_perfis'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfil_associacoes', to='formularios.formulario')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_formularios', to='projetos.perfil')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='formularios',
            field=models.ManyToManyField(blank=True, related_name='perfis', through='projetos.PerfilFormulario', to='formularios.formulario'),
        ),
        migrations.AddConstraint(
            model_name='perfilformulario',
            constraint=models.UniqueConstraint(fields=('perfil', 'formulario'), name='uniq_perfil_formulario'),
        ),
    ]
