# Generated by Django 6.1 on 2026-08-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0008_remove_perfil_formulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('CAPTACAO', 'Captação'), ('RESPOSTAS', 'Respostas')], default='CAPTACAO', help_text='Captação: perfil recebe gente nova (link público, associação manual/lote). Respostas: perfil só coleta respostas de quem já foi captado antes.', max_length=20),
        ),
    ]
