# Generated by Django 6.1 on 2026-08-18 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0009_perfil_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='qtd_categorias_escolha',
            field=models.PositiveSmallIntegerField(default=3, help_text='Quando este perfil é de Captação e tem mais categorias de formulário do que esse número, a pessoa escolhe essa quantidade de categorias antes de responder — só os formulários das categorias escolhidas abrem pra ela.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='perfil',
            name='texto_boas_vindas_categorias',
            field=models.TextField(blank=True, help_text='Texto opcional mostrado acima da pergunta, na tela de escolha de categorias.'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='texto_escolha_categorias',
            field=models.CharField(blank=True, default='Escolha 3 categorias que tem mais domínio para responder perguntas e participar de pesquisas:', help_text='Pergunta mostrada na tela de escolha de categorias (em branco usa o texto padrão).', max_length=300),
        ),
    ]
