# Generated by Django 6.1 on 2026-08-19 03:13

import django.db.models.deletion
from django.db import migrations, models

# Segmento antigo (lista fixa no código) → nome da CategoriaFormulario
# equivalente já cadastrada — usado só pra não perder o dado de quem já
# tinha um segmento preenchido. "OUTRO" e qualquer código sem categoria
# cadastrada com o mesmo nome ficam sem categoria (mais honesto que
# adivinhar uma associação errada).
_SEGMENTO_PARA_CATEGORIA = {
    "SAUDE": "Saúde",
    "ALIMENTACAO": "Alimentação",
    "BANCO": "Banco",
    "TECNOLOGIA": "Tecnologia",
}


def preencher_categoria_a_partir_do_segmento(apps, schema_editor):
    Projeto = apps.get_model("projetos", "Projeto")
    CategoriaFormulario = apps.get_model("formularios", "CategoriaFormulario")
    categorias_por_nome = {c.nome: c for c in CategoriaFormulario.objects.all()}
    for projeto in Projeto.objects.exclude(segmento="").exclude(segmento__isnull=True):
        nome_categoria = _SEGMENTO_PARA_CATEGORIA.get(projeto.segmento)
        categoria = categorias_por_nome.get(nome_categoria) if nome_categoria else None
        if categoria is not None:
            projeto.categoria = categoria
            projeto.save(update_fields=["categoria"])


def reverter_categoria_para_segmento(apps, schema_editor):
    # Reversão não recupera o código antigo de verdade (o mapeamento não é
    # 1:1 nos dois sentidos — várias categorias cadastradas não tinham
    # equivalente na lista fixa antiga) — deixa `segmento` vazio pra quem
    # tinha `categoria`, é o melhor que dá pra fazer sem inventar dado.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0007_categoria_formulario'),
        ('projetos', '0010_perfil_qtd_categorias_escolha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to='formularios.categoriaformulario'),
        ),
        migrations.RunPython(preencher_categoria_a_partir_do_segmento, reverter_categoria_para_segmento),
        migrations.RemoveField(
            model_name='projeto',
            name='segmento',
        ),
    ]
