# Generated by Django 6.1 on 2026-08-09 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Termo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('CONSENTIMENTO', 'Termo de Consentimento'), ('CONTRATO', 'Contrato'), ('CONFIDENCIALIDADE', 'Termo de Confidencialidade'), ('CESSAO_IMAGEM_VOZ', 'Cessão de Imagem e Voz')], max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='VersaoTermo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(max_length=20)),
                ('texto', models.TextField()),
                ('inicio_vigencia', models.DateField()),
                ('fim_vigencia', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('VIGENTE', 'Vigente'), ('SUBSTITUIDA', 'Substituída'), ('AGENDADA', 'Agendada'), ('EXPIRADA', 'Expirada')], default='VIGENTE', max_length=20)),
                ('publicado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versoes_publicadas', to=settings.AUTH_USER_MODEL)),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='termos.termo')),
            ],
            options={
                'ordering': ['-publicado_em'],
            },
        ),
        migrations.CreateModel(
            name='LogAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quando', models.DateTimeField(auto_now_add=True)),
                ('acao', models.CharField(max_length=200)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='termos.versaotermo')),
            ],
            options={
                'ordering': ['-quando'],
            },
        ),
        migrations.AddConstraint(
            model_name='versaotermo',
            constraint=models.UniqueConstraint(fields=('termo', 'versao'), name='uniq_termo_versao'),
        ),
    ]
