# Generated by Django 6.1 on 2026-08-12 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_alter_participante_consentimento_versao'),
        ('termos', '0002_seed_documento_lgpd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AceiteTermo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('PUBLICO', 'Cadastro público (a própria pessoa aceitou)'), ('STAFF', 'Registrado por um operador do sistema')], max_length=10)),
                ('aceito_em', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceites_termos', to='pessoas.participante')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aceites_termos_registrados', to=settings.AUTH_USER_MODEL)),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aceites_registrados', to='termos.versaotermo')),
            ],
            options={
                'ordering': ['-aceito_em'],
            },
        ),
    ]
