# Generated by Django 6.1 on 2026-08-09 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seed_exclusao_permissoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaAvisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triagem_pendente', models.BooleanField(default=True, verbose_name='Triagem de participantes pendente')),
                ('projetos_vagas', models.BooleanField(default=True, verbose_name='Projetos com vagas em aberto e campo próximo')),
                ('termos_vencendo', models.BooleanField(default=True, verbose_name='Termos vigentes perto de expirar')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencia_avisos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AvisoDispensado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100)),
                ('conteudo', models.CharField(blank=True, max_length=255)),
                ('dispensado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_dispensados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'chave', 'conteudo'), name='uniq_aviso_dispensado')],
            },
        ),
    ]
