"""
Django settings for bancopessoas project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Railway define essa variável automaticamente em todo serviço publicado —
# é o jeito mais simples de saber "isso está rodando em produção ou não"
# sem precisar configurar mais nada manualmente.
IS_RAILWAY = bool(os.environ.get('RAILWAY_ENVIRONMENT'))
RAILWAY_PUBLIC_DOMAIN = os.environ.get('RAILWAY_PUBLIC_DOMAIN')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-aec&sfm)i*7^%txjv_eh*=jgjaae3cg5c(r7@kr#^v^txt4_*&'

# SECURITY WARNING: don't run with debug turned on in production!
# Localmente (sem RAILWAY_ENVIRONMENT) continua True, igual sempre foi — em
# produção no Railway já nasce False por segurança, a menos que DEBUG=True
# seja setado manualmente na aba Variables (não recomendado).
DEBUG = os.environ.get('DEBUG', 'False' if IS_RAILWAY else 'True') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]
if RAILWAY_PUBLIC_DOMAIN:
    ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)
if not IS_RAILWAY:
    ALLOWED_HOSTS += ['localhost', '127.0.0.1']
elif not ALLOWED_HOSTS:
    # Primeiro deploy, antes de gerar o domínio público no Railway: libera
    # qualquer subdomínio *.up.railway.app para não travar o healthcheck.
    ALLOWED_HOSTS.append('.up.railway.app')

CSRF_TRUSTED_ORIGINS = [f'https://{RAILWAY_PUBLIC_DOMAIN}'] if RAILWAY_PUBLIC_DOMAIN else []

if IS_RAILWAY:
    # O Railway termina o HTTPS na borda e repassa pra aplicação em HTTP simples
    # com esse cabeçalho indicando o protocolo original — sem isso o Django acha
    # que toda requisição é insegura.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'pessoas',
    'projetos',
    'participacoes',
    'auditoria',
    'termos',
    'core',
]

AUTH_USER_MODEL = 'accounts.Usuario'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bancopessoas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.alertas',
            ],
        },
    },
]

WSGI_APPLICATION = 'bancopessoas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Banco PostgreSQL (RDS) — schema "pessoas".
# AVISO: credenciais mantidas direto no código por decisão do usuário (sem .env).
# Isso significa que, se este repositório for versionado publicamente, a senha do banco
# fica exposta no histórico do git. Ver docs/SDD.md para detalhes.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'df3l815t7pjmsl',
        'USER': 'ukdsmqgidk3og',
        'PASSWORD': 'p3f70b713d6f748d6057d923ec10e1fc77ee4aebf0e57aa28772cad5b0d85b652',
        'HOST': 'c2hbg00ac72j9d.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path=pessoas,public',
        },
        # Reutiliza conexões por até 30 min (equivalente a pool_recycle do SQLAlchemy).
        'CONN_MAX_AGE': 1800,
        # Testa a conexão antes de reusar (equivalente a pool_pre_ping).
        'CONN_HEALTH_CHECKS': True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'core:home'
LOGOUT_REDIRECT_URL = 'accounts:login'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
