# Generated by Django 6.1 on 2026-08-09 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('ANALISE_PERFIL', 'Análise de Perfil'), ('PREENCHIMENTO_DADOS', 'Preenchimento de Dados'), ('CAPTACAO_MATERIAL', 'Captação de Material'), ('ENTREVISTA', 'Entrevista'), ('PAGO', 'Pago')], default='ANALISE_PERFIL', max_length=30)),
                ('status', models.CharField(blank=True, choices=[('APROVACAO', 'Aprovação'), ('BACKUP', 'Backup'), ('DESISTENCIA', 'Desistência'), ('NAO_COMPARECEU', 'Não compareceu'), ('NAO_APROVADO', 'Não aprovado'), ('FORA_PERFIL', 'Fora do perfil')], max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('etapa_atualizada_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='pessoas.participante')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='projetos.projeto')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participacoes_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comunicacao', models.PositiveSmallIntegerField()),
                ('pontualidade', models.PositiveSmallIntegerField()),
                ('repertorio', models.PositiveSmallIntegerField()),
                ('nota_geral', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('avaliado_em', models.DateTimeField(auto_now_add=True)),
                ('avaliado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('participacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='participacoes.participacao')),
            ],
        ),
        migrations.AddConstraint(
            model_name='participacao',
            constraint=models.UniqueConstraint(fields=('participante', 'projeto'), name='uniq_participante_projeto'),
        ),
    ]
