# Generated by Django 6.1 on 2026-08-13 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participacoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='nota_geral',
        ),
    ]
