# Generated by Django 6.1 on 2026-08-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participacoes', '0005_finalizar_perfil_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacao',
            name='etapa',
            field=models.CharField(choices=[('PREENCHIMENTO_DADOS', 'Preenchimento de Dados'), ('ANALISE_PERFIL', 'Análise de Perfil'), ('CAPTACAO_MATERIAL', 'Captação de Material'), ('ENTREVISTA', 'Entrevista'), ('PAGO', 'Pago')], default='ANALISE_PERFIL', max_length=30),
        ),
    ]
