# Generated by Django 6.1 on 2026-08-20 23:19

import django.utils.timezone
from django.db import migrations, models


def preencher_data_aplicacao_com_criado_em(apps, schema_editor):
    # A `AddField` acima já preenche toda participação existente com "agora"
    # (o `default` é avaliado na hora de rodar a migração) — pra quem já
    # existia, `criado_em` é uma estimativa bem melhor de quando a pesquisa
    # foi aplicada do que o instante em que essa migração rodou.
    Participacao = apps.get_model("participacoes", "Participacao")
    Participacao.objects.update(data_aplicacao=models.F("criado_em"))


def reverter_preenchimento(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('participacoes', '0006_alter_participacao_etapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacao',
            name='data_aplicacao',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.RunPython(preencher_data_aplicacao_com_criado_em, reverter_preenchimento),
    ]
