# Generated by Django 6.1 on 2026-08-21 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participacoes', '0007_participacao_data_aplicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacao',
            name='etapa',
            field=models.CharField(choices=[('PREENCHIMENTO_DADOS', 'Preenchimento de Dados'), ('ANALISE_PERFIL', 'Análise de Perfil'), ('CAPTACAO_MATERIAL', 'Captação de Material'), ('ENTREVISTA', 'Entrevista'), ('PAGO', 'Pago')], db_index=True, default='ANALISE_PERFIL', max_length=30),
        ),
        migrations.AlterField(
            model_name='participacao',
            name='status',
            field=models.CharField(blank=True, choices=[('APROVACAO', 'Aprovação'), ('BACKUP', 'Backup'), ('DESISTENCIA', 'Desistência'), ('NAO_COMPARECEU', 'Não compareceu'), ('NAO_APROVADO', 'Não aprovado'), ('FORA_PERFIL', 'Fora do perfil')], db_index=True, max_length=20),
        ),
    ]
